[package]
name = "swag"
version = "0.1.0"
description = "General Purpose Sliding Window Aggregator"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
